name: Ruby Gem

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.8'

    - name: Install Bundler
      run: |
        gem install bundler -v '~> 2.4.0'

    - name: Build and Push Gem
      env:
        GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build your_actual_gem_name.gemspec
        gem push --key github --host https://rubygems.pkg.github.com/${OWNER} your_actual_gem_name-*.gem
